# This is a basic workflow to help you get started with Actions

name: t2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: dkershner6/post-api-call-action@v1
        with:
           url: https://xiaodan.teams.itsma-ng.com/xie/v1/namespaces/555500000/listener?scenarioId=372ea25c-1a6d-41f5-abe9-57d416577c28&integrationId=3f3de5d9-a0fb-400a-939a-11849aa60f74&authType=url&sig=AAEzB8+zzCIij1wn5YWqrX9e8nyFoIio0Pll5+P4YGx1vL0qBQ3psquP9EEfmWQ4IYnjQTkmzaZJNwMsCXBjH36Kp68X9Z31vFTbqnsVRgYxjoLpBPcdSZo2
        #  url: https://wenxiu.teams.itsma-ng.com/xie/v1/namespaces/100000002/listener?scenarioId=7c7675a5-9bcb-41a4-8ef4-eeb75a8dadb8&integrationId=cf366218-959e-43eb-94b6-f2daa3f4f567&authType=url&sig=AAGkiSuQz1IUlmChlmcF9QxMVTD45vNttKUWkhafCsP8fUbgW5o60I41HvJboICCX0Wz2j8sVl0Sghp49ejOOlPEYsk14wn27pQyh2+RhRL5vEYK77qPAutt/BRhlLLMhpf8t1usY8278o4ArpExJSvPMtWc1/6abzpjgStB74jSfpLnJzUCLGxBe8HnVKvI
           data: "{\"runId\":\"1234\"}"
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Lwenxiu
          minimum-approvals: 1
          issue-title: "action approval"
          issue-body: "Please approve"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
