on:
  push:
    branches:
    - master
jobs:
  my_job:
    name: job1
    runs-on: ubuntu-latest
    steps: 
#       - uses: distributhor/workflow-webhook@v2
#         env:
#           webhook_url: https://shc-sma-cd48.hpeswlab.net/xie/v1/namespaces/100000002/listener?scenarioId=72beed7a-370d-4e48-9d7f-4d89ff4a16d3&integrationId=1151b717-7e49-47f6-9f0b-a7855e092308&authType=basic&sig=AAHsAv/IOvWMtpAgd4oP50VagmxpQJ+nfqf2ttVUT5yA+o+4cEOm5KedcaSkxIn5vOB936d+NIBNePB2Sa4P+51C2Oueklv4fhTrKgRiAZS8gZ/K+2Di6i/QO5vY57wh1fDarh/vkLDEzTM%3D
#           webhook_auth: "suite-admin:pat_8Hvr1nWdA8YdThFg1uAgKuioj3w9WoKx"
#           verify_ssl: false
#       - uses: dkershner6/post-api-call-action@v1
#         with:
#             url: https://wenxiu.teams.itsma-ng.com/xie/v1/namespaces/100000002/listener?scenarioId=7c7675a5-9bcb-41a4-8ef4-eeb75a8dadb8&integrationId=cf366218-959e-43eb-94b6-f2daa3f4f567&authType=url&sig=AAGkiSuQz1IUlmChlmcF9QxMVTD45vNttKUWkhafCsP8fUbgW5o60I41HvJboICCX0Wz2j8sVl0Sghp49ejOOlPEYsk14wn27pQyh2+RhRL5vEYK77qPAutt/BRhlLLMhpf8t1usY8278o4ArpExJSvPMtWc1/6abzpjgStB74jSfpLnJzUCLGxBe8HnVKvI
#             data: "{\"runId\":GITHUB_RUN_ID,\"job\":GITHUB_JOB,\"workflow\":GITHUB_WORKFLOW}"
      - run: curl -X POST "https://wenxiu.teams.itsma-ng.com/xie/v1/namespaces/100000002/listener?scenarioId=c528f9d6-0892-4ed1-a79e-cefa70b5a15f&integrationId=9fa9d067-cf59-47ba-8890-f7a9c840711e&authType=url&sig=AAE6+xVzNvQ531XUkXM6Wk0Sfud0fi1HSiXRKnR9ZdaLg9ydb+L4qCMil3buU4ydo9ZnWvEjpZPYg6/nDNTzs9zhTEz+2fF6E7UdhuSrh03crg7XI8ohG3KMS97+AWGKCjw/YkQyCGA//nVwosvzP1j6BAPeKi7z2Aog4MaTqZGogIf0wHoMiLS3ENaLBBGx" -d '{"runId":${{env.GITHUB_RUN_ID}},"job":${{env.GITHUB_JOB}},"workflow":${{env.GITHUB_WORKFLOW}}}'
